<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>KfuPet</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\icon\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.0.5</Version>
    <Authors>Grey Bullet Technology Studio</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon\Startlogo.png" />
    <Resource Include="Assets\icon\app.ico" />
    <Resource Include="Assets\icon\tray.ico" />
    <Resource Include="Characters\logo.png" />
  </ItemGroup>

</Project>
